language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

sudo: false

install:
    - composer install --prefer-dist --dev

script:
    - ant -keep-going

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
